### ISSUE TITLE
第一次載入會跳到局域網鏈接上去，第二次會直接崩端

### ISSUE THREAD

**Issue by wfwfwfw** [RPMTW/RPMTW-Update-Mod#44]
[minecraft-exported-logs-2021-06-17T16-40-01.log](https://github.com/RPMTW/RPMTW-Update-Mod/files/6668734/minecraft-exported-logs-2021-06-17T16-40-01.log)

**Comment by SiongSng** [comment]
@wfwfwfw 這是伺服器的崩潰報告還是客戶端?

**Comment by wfwfwfw** [comment]
客户端




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RPMTW/RPMTW-Update-Mod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RPMTW/RPMTW-Update-Mod] 第一次載入會跳到局域網鏈接上去，第二次會直接崩端 (#44)





 
@wfwfwfw 這是伺服器的崩潰報告還是客戶端?

**Comment by SiongSng** [comment]
根據崩潰報告應該是無法連線上github伺服器，所以無法檢測RPMTW的版本，我猜可能是網路問題?

**Comment by wfwfwfw** [comment]
载入完成加入世界的时候，依旧会显示这个



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月26日(星期六) 中午12:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RPMTW/RPMTW-Update-Mod] 第一次載入會跳到局域網鏈接上去，第二次會直接崩端 (#44)





 
Closed #44.
