### ISSUE TITLE
每個模組名字前面都有"禮9禮o"

### ISSUE THREAD

**Issue by derek9641** [RPMTW/RPMTW-Update-Mod#56]
如提
每個模組名字前面都有禮9禮o
不知道為甚麼
Minecraft 版本: 1.16.5 fabric
模組包: All of Fabric 3

![スクリーンショット 2021-07-19 181749](https://user-images.githubusercontent.com/55919922/126127617-4ac7aa16-a4a3-49df-9ea5-ed225ec6de15.png)

**Comment by SiongSng** [comment]
之前我遊玩的時候也有遇到這個問題 我也不太清楚，但我能確定與RPMTW無關，只要把語言切成中文模組名稱他就會顯示這樣
如有其他問題或想要討論Minecraft可以到我們的官方Discord
